[package]
name = "asdf"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[profile.release]
debug = 1
strip = "none" # Prevents Cargo from stripping anything (use with caution)

[profile.dev]
strip = "none" # Prevents Cargo from stripping anything (use with caution)

[dependencies]

